### PR TITLE
WIP: Feature/GitHub actions ci

### PR DESCRIPTION
**Pull request by edmundmiller**
The releases aren't working and still waiting on #33 to get merged for testing to be allowed. I'd also like to add linting in see #49.

### CODE REVIEW

**Comment by edmundmiller** [comment]
I think my release rules are failing because I'm not running them in the `jellyfinclient` dir. I'm new to the project though and can't tell from the docs.

https://github.com/Emiller88/jellyfin-react-client/runs/385250413

**Comment by EraYaN** [comment]
We use Azure Pipelines for all our repos, would you mind transforming this one? Otherwise I can take a stab at it.

**Comment by edmundmiller** [comment]
@EraYaN Sure I'll give it a go.

**Comment by edmundmiller** [comment]
@EraYaN I haven't used azure pipelines before, so I don't know a good way to test it, and some finer points may be off. I used the `jellyfin-web`'s config as a starting point.

**Comment by EraYaN** [comment]
When it's merged I'll set it up. And then you can play around with tests in a new PR if you want. So it's always best effort the first time. I have yet to find a better way, maybe adding an empty one when creating the repo or something.

**Pull request closed without merging**
